development:
    echonest:
        key: "2FOIUUMCRLFMAWJXT"

    google:
        key: "AIzaSyD50sJyFXZHBBvBUbmEwaS4elZOCVE7wMU" 

    playlist:
        pagesize: 5

    redis:
       url: '127.0.0.1:6379' 

production:
    redis:
        url: 'redis://redistogo:375083b91d787fdfeaf5e587de0715ae@tarpon.redistogo.com:9386/'
